// autogenerated

// todo - add validation of the structure at startup
#pragma once

#include <cstdint>

struct playercreateinfo_action
{
    uint8_t race;
    uint8_t class_; // reserved keyword, what now!
    uint16_t button;
    uint32_t action;
    uint16_t type;
};
